theme: jekyll-theme-midnight
title: Алексей Дёмин
description: Сертифицированный Laravel-разработчик с 10-летним опытом
show_downloads: true
links:
  resume_url: https://disk.yandex.ru/i/d1u_ELrmf1OShQ
  cert_url: https://disk.yandex.ru/i/djwRoHPqEO7XVg
  upwork_url: https://disk.yandex.ru/i/i8q4Kob-m8R3dQ
  github_url: https://github.com/alex-demin
  linkedin_url: https://www.linkedin.com/in/demin-online/
  laracasts_url: https://laracasts.com/@AlexDemin
  telegram_url: https://t.me/g0thham