theme: jekyll-theme-hacker
title: Алексей Дёмин
description: Сертифицированный Laravel-разработчик с 10-летним опытом
links:
  resume_url: https://disk.yandex.ru/i/d1u_ELrmf1OShQ
  cert_url: https://disk.yandex.ru/i/djwRoHPqEO7XVg