theme: jekyll-theme-hacker
title: Алексей Дёмин / Certified Laravel Developer
description: Пилю автоматизацию, API интеграции для бизнеса
links:
  resume_url: https://disk.yandex.ru/i/d1u_ELrmf1OShQ
  cert_url: https://disk.yandex.ru/i/djwRoHPqEO7XVg