theme: jekyll-theme-hacker
title: Алексей Дёмин
description: Certified Laravel Developer, бекенд-разработчик. Пилю автоматизацию, API интеграции для бизнеса. Фриланс и удаленная работа.
show_downloads: true
github:
  zip_url: http://demin.online/resume-laravel-developer-alex-demin.zip
  cert_url: http://demin.online/laravel-certificate-alex-demin-2018-07-05.pdf