theme: jekyll-theme-hacker
title: Алексей Дёмин - Certified Laravel Developer
description: Автоматизация & API интеграции для малого и среднего бизнеса
show_downloads: false
github:
  zip_url: http://demin.online/alex_demin_certified_laravel_developer_resume.zip